import { inter } from '@/config/fonts';
import { Provider } from '@/provider/Provider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s | Joselu Shop',
    default: 'Joselu Shop',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${inter.className} antialiased`}>{children}</body>
      </Provider>
    </html>
  );
}
